CREATE TABLE book_clubs (
    club_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    topic TEXT,
    currently_reading TEXT,
    next_meeting DATE
);