CREATE TABLE book_clubs (
    club_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    topic TEXT,
    currently_reading TEXT,
    next_meeting DATE,
    member_one INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    member_two INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    member_three INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    member_four INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    member_five INTEGER REFERENCES users(user_id) ON DELETE CASCADE
);